# Python Tutorial


Data Types

1) Lists
2) Sets
3)Tuples
4) Dictionaries

Lists

List are index value,
Lists are mutable,
Values in lists are separated by comma

In [1]:
lst = [1,2,3,4]

In [2]:
len(lst)

4

# List Functions

In [3]:
lst.append(5)
lst

[1, 2, 3, 4, 5]

In [4]:
lst.insert(2,'Karan')
lst

[1, 2, 'Karan', 3, 4, 5]

In [5]:
lst.remove('Karan') #Only removes first occurence of the value

In [6]:
lst

[1, 2, 3, 4, 5]

In [7]:
lst2 = [6,7,8]
lst.extend(lst2)
lst

[1, 2, 3, 4, 5, 6, 7, 8]

Difference Between Append & Extend - Append basically add entire thing in list. On the other hand extend basically add each elements as single only

In [8]:
del lst[1]
lst

[1, 3, 4, 5, 6, 7, 8]

In [9]:
a = lst.pop(1)
a

3

In [10]:
if 6 in lst:
    print('Yes')
else:
    print('No')

Yes


In [11]:
if 10 in lst:
    print('Yes')
else:
    print('No')

No


In [12]:
lst.reverse()
lst

[8, 7, 6, 5, 4, 1]

In [13]:
lst.sort(reverse=False)
lst

[1, 4, 5, 6, 7, 8]

In [3]:
s = "one,Two,Thre,Fourth"
ss = s.split(',')
ss

['one', 'Two', 'Thre', 'Fourth']

In [15]:
s = "one Two Thre Fourth"
ss = s.split()
ss

['one', 'Two', 'Thre', 'Fourth']

# List Slicing

In [16]:
lst[1]

4

In [17]:
lst

[1, 4, 5, 6, 7, 8]

In [18]:
lst[:]

[1, 4, 5, 6, 7, 8]

In [19]:
lst[0:6:2]

[1, 5, 7]

In [20]:
lst1 = [1,2,3,4]
lst2 = [5,6,7,8]
lst = lst1+lst2
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [21]:
lst.count(9)

0

In [22]:
for e in lst:
    print(e)

1
2
3
4
5
6
7
8


# List looping and list comprehension

In [23]:
l = []
for i in range(10):
    l.append(i**2)
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [24]:
l = [i**2 for i in range(10)]
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [25]:
x = [-10,-20,10,20,30]

a = [i*2 for i in x]
print(a)
b = [i for i in x if i>=0]
print(b)
c=[(i,i**2) for i in x]
print(c)

[-20, -40, 20, 40, 60]
[10, 20, 30]
[(-10, 100), (-20, 400), (10, 100), (20, 400), (30, 900)]


In [26]:
matrix = [[1,2,3],
         [4,5,6],
         [7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
t = []
for i in range(3):
    l=[]
    for row in matrix:
        l.append(row[i])
    t.append(l)
t

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [28]:
t = [[row[i] for row in matrix] for i in range(3)]
t

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

# Tuples

Tuples is similar to list. But Tuples are inmutable

In [29]:
t = (1,2,3,4)
t

(1, 2, 3, 4)

In [30]:
t[1]

2

In [31]:
b = ('Karan')
print(type(b))

<class 'str'>


In [32]:
c = ('Karan',)
print(type(c))

<class 'tuple'>


If there is only one value in paranthesis, then you need to end it with comma. Otherwise that would be treated as string only

# Tuples Slicing & Functions

In [33]:
t[0::2]

(1, 3)

In [34]:
t = (1,2,3,4,[5,6,7])
t[4][1] = 'Karan'
t

(1, 2, 3, 4, [5, 'Karan', 7])

In [35]:
t1 = (1,2,3,4)
t2 = (5,6,7,8)
t3 = t1+t2
t3

(1, 2, 3, 4, 5, 6, 7, 8)

In [36]:
del t

In [37]:
t3.count(2)

1

In [38]:
t3.index(3)

2

In [39]:
t3

(1, 2, 3, 4, 5, 6, 7, 8)

In [40]:
if 1 in t3:
    print('Yes')

Yes


In [41]:
max(t3)

8

In [42]:
min(t3)

1

# sets

Set is unordered and cannot be indexed. It is mutable. Set can be used to perform mathematical set of operations like union, intersection, symmetric difference etc.

In [43]:
s = {1,2,3,4,5,6,1,2,3,4,5,6}
s

{1, 2, 3, 4, 5, 6}

In [44]:
s = set([1,2,3,4,5,6])
s

{1, 2, 3, 4, 5, 6}

In [45]:
s.add(7)
s

{1, 2, 3, 4, 5, 6, 7}

# Sets Functions

In [46]:
n = [1,2,3,4,5,6,7,8,9,'Karan']
s.update(n)
s

{1, 2, 3, 4, 5, 6, 7, 8, 9, 'Karan'}

In [47]:
s.discard(2)
s

{1, 3, 4, 5, 6, 7, 8, 9, 'Karan'}

In [48]:
s.remove(5)
s

{1, 3, 4, 6, 7, 8, 9, 'Karan'}

# Python Set Operations

Union

In [49]:
set1 = {1,2,3,4,5}
set2 = {3,4,5,6,7}

print(set1|set2)

{1, 2, 3, 4, 5, 6, 7}


In [50]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7}

Intersection

In [51]:
print(set1&set2)

{3, 4, 5}


In [52]:
set1.intersection(set2)

{3, 4, 5}

Difference

In [53]:
print(set1-set2)

{1, 2}


In [54]:
set1.difference(set2)

{1, 2}

In [55]:
print(set2-set1)

{6, 7}


In [56]:
set2.difference(set1)

{6, 7}

Symmetric Difference

In [57]:
set1.symmetric_difference(set2)

{1, 2, 6, 7}

In [58]:
set2.symmetric_difference(set1)

{1, 2, 6, 7}

Subset

In [59]:
x = {1,2,3,4,5}
y = {2,3}

print(x.issubset(y))
print(y.issubset(x))

False
True


# Dictionary

Python dictionary is an unordered collection of items. While other compound data types have only value as an element, a dictionary has a key; value pair

In [60]:
mdict = {1:'Karan', 2:'Vikas'}
mdict

{1: 'Karan', 2: 'Vikas'}

# Dictionary functions

In [61]:
mdict.keys()

dict_keys([1, 2])

In [62]:
mdict.values()

dict_values(['Karan', 'Vikas'])

In [63]:
mdict.get(2)

'Vikas'

In [64]:
for i in mdict.values():
    print(i)

Karan
Vikas


In [65]:
for i in mdict.keys():
    print(i)

1
2


In [66]:
mydict = dict([(1,'Ram'),(2,'Shyam')])
mydict

{1: 'Ram', 2: 'Shyam'}

In [67]:
mydict.get(1)

'Ram'

In [68]:
mydict[1]

'Ram'

Changing value with the help of Key

In [69]:
mydict[1] = 'Karan'
mydict

{1: 'Karan', 2: 'Shyam'}

In [70]:
mydict['3'] = 'Abhishek'
mydict

{1: 'Karan', 2: 'Shyam', '3': 'Abhishek'}

In [71]:
mydict.clear()
mydict

{}

In [72]:
mydict = dict([(1,'Ram'),(2,'Shyam')])
mydict

{1: 'Ram', 2: 'Shyam'}

In [73]:
mydict.items()

dict_items([(1, 'Ram'), (2, 'Shyam')])

In [74]:
blankdict = {}.fromkeys([1,2,3],0)
blankdict

{1: 0, 2: 0, 3: 0}

In [75]:
for i,j in mydict.items():
    print('Key '+ str(i) ,'Values '+j)

Key 1 Values Ram
Key 2 Values Shyam


In [76]:
i = [2,3,1,5,6,7,4]
i

[2, 3, 1, 5, 6, 7, 4]

In [77]:
for x in range(len(i)-1,0,-1):
    for y in range(x):
        if i[y]>i[y+1]:
            temp = i[y]
            i[y] = i[y+1]
            i[y+1] = temp
print(i)

[1, 2, 3, 4, 5, 6, 7]


In [78]:
s1 = 'Good Morning'
s2 = s1.replace('Good','Bad')
s2

'Bad Morning'

In [79]:
s= 'madam'
s

'madam'

In [80]:
ss = list(s)
ss

['m', 'a', 'd', 'a', 'm']

In [81]:
for y in range(len(i)):
    print(y)

0
1
2
3
4
5
6


# String Functions

In [82]:
s1 = 'Karan'
s2 = 'Kaushik'
print(s1,s2)

Karan Kaushik


In [83]:
counts = 0
for i in s3.upper():
    if i=='K':
        counts+=1
    
print('Total counts ', counts)

NameError: name 's3' is not defined

# String Membership Tests

In [ ]:
print('K' in s3.upper())

In [ ]:
print('KA' in s3.upper())

In [ ]:
s3.lower()


In [ ]:
s = 'This will split all the words in a list'
s.split()


In [ ]:
s=['This', 'will','join','all','the','words']
' '.join(s)

In [ ]:
st = 'Good Morning'
st.find('Mo')

# Python programe to check whehter a string is palandrome or not 

In [2]:
mystr = 'madam'
revstr = reversed(mystr)

if mystr==revstr:
    print('Yes')
else:
    print('No')

if list(mystr)==list(revstr):
    print('Yes it is palandrome')
else:
    print('No it is not palandrome')

No
Yes it is palandrome


In [3]:
revstr

In [1]:
a=2
b=2
if a==b:
    print('Yes')
else:
    print('No')

Yes


In [ ]:
s = 'Karan'
ss = list(s)
ss

In [ ]:
s.isalnum()

# Numpy Tutorials

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# What is an Array?

An array is a data structure that stores values of same data types. In python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, array in python can only contain values corresponding to same data type.

In [5]:
import numpy as np

In [ ]:
my_lst = [1,2,3,4]
arr = np.array(my_lst)
arr

In [ ]:
type(arr)

In [ ]:
arr.shape

In [ ]:
arr.reshape(2,3)

In [ ]:
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]
l3 = [6,7,8,9,10]
arr = np.array([l1,l2,l3])
arr

In [ ]:
arr.shape

In [ ]:
arr.reshape(5,3)

In [ ]:
arr.shape

# Numpy Array Indexing

In [ ]:
arr

In [ ]:
arr[1]

In [ ]:
arr[0::2]

Indexing in two dimensional array

In [ ]:
arr[0:3,1:3]

In [6]:
arr2=arr.reshape(5,3)
arr2

NameError: name 'arr' is not defined

In [ ]:
arr2[2:4,1:]

In [ ]:
arr2[2:4,0:2]

In [7]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
arr2 = arr.copy()
arr2

In [4]:
arr = np.arange(0,9).reshape(3,3)
arr

NameError: name 'np' is not defined

In [ ]:
arr[0] = 2
arr

# Some useful condition in exploratory data analysis
## Very Important

In [8]:
val=2
arr>val

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
arr*val

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr/val

In [10]:
arr%val

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [ ]:
s = [1,2,3,4,5]
for i in s:
    print(i/2)

In [ ]:
arr

In [11]:
arr[(arr>2) & (arr<=6)] #Most Important

array([3, 4, 5, 6])

In [ ]:
arr

In [ ]:
arr1 = np.arange(0,9).reshape(3,3)
arr1
arr2 = np.arange(10,19).reshape(3,3)
arr2

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr3 = arr1*arr2   #Simple Multiplication
arr3

In [ ]:
np.ones(4,dtype=int)

In [ ]:
arr = np.zeros(16).reshape(4,4)
arr

In [ ]:
arr[0:1,0:] = 1
arr[-1:,0:] = 1
arr

In [ ]:
arr = np.random.rand(3,3)
arr

In [ ]:
arr=np.random.randn(4,4)
arr

In [ ]:
arr = np.random.randint(0,100,8).reshape(4,2)
arr

In [ ]:
arr = np.random.random_sample(2)
arr

# Pandas Tutorial 

Pandas is an open source, providing high performance, easy to use data structures and data analysis tools for the python programming language. Please note that Pandas & Numpy are must for explotary data analysis.

Agenda:
. What is Data Frame? <br>
. What is Data Series? <br>
. Different operation in Pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index = [1,2,3,4,5],columns = ['A','B','C','D'])
df

In [ ]:
b =df.iloc[0:,1:]
b

In [ ]:
a = df.loc[1]
a

In [ ]:
print(type(a))
print(type(b))

In [ ]:
df.shape

In [ ]:
df.iloc[:,1:]

Convert Dataframe into array

In [ ]:
df.iloc[:,1:].values

In [ ]:
df.isnull().sum()

In [ ]:
df['A'].value_counts()

In [ ]:
a = list(df['A'].unique())
a

In [ ]:
df

In [ ]:
df[['C','D']]

In [ ]:
for i,j in zip(df.iloc[0:,0],df.iloc[0:,1]):
    print(i,j)

In [ ]:
df

# Deeper understanding of Pandas

In [ ]:
df = pd.read_csv("D:\Machine Learning - Course\Sample Data Sets\mercedesbenz.csv")

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df['X0'].value_counts()

In [ ]:
df.head()

In [ ]:
df.loc[df['y']>130].count()['ID']

In [ ]:
a = df.loc[df['y']>130].count()['ID']
a
print(type(a))
a

In [ ]:
df.corr()

# CSV

In [ ]:
from io import StringIO, BytesIO

In [ ]:
data = ('col1,col2,col3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3')

In [ ]:
type(data)

In [ ]:
pd.read_csv(StringIO(data))

In [ ]:
df = pd.read_csv(StringIO(data),usecols = ['col1','col2'])
df

In [ ]:
df.reset_index(drop=False)

In [ ]:
df.to_csv('Test1.csv')

In [ ]:
df = pd.read_csv(StringIO(data),dtype=object)
df

In [ ]:
df['col1'][1]

In [ ]:
df.describe()

In [ ]:
df = pd.read_csv(StringIO(data),dtype={'col1':object,'col2':object,'col3':int})
df

In [ ]:
df.dtypes

In [ ]:
df['col1'][0:]

In [ ]:
data = ('index,a,b,c\n'
       '4,apple,bat,5.7\n'
       '8,orangecow,10')

In [ ]:
df = pd.read_csv(StringIO(data),index_col=0)
df

In [ ]:
data = ('a,b,c\n'
       '4,apple,5.7\n'
       '8,orange,10')

In [ ]:
df = pd.read_csv(StringIO(data),index_col=False)
df

In [ ]:
df=pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',sep='\t')
df.head()

# Read Json to CSV

 # Json is basically a combination of key value pairs

In [ ]:
data = '{"employee_name":"James","Email":"James@gmail.com"}'

In [ ]:
data

In [ ]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)
                
df.head()

In [ ]:
df.to_csv('Wine.csv')

In [ ]:
df.to_json(orient="records")

# Reading HTML Content

In [ ]:
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
df=pd.read_html(url)
type(df)

In [ ]:
df[0]

In [ ]:
df2=df[0]
df2.head()

In [ ]:
df2.loc[df2['Bank Name']=='The First State Bank']

In [ ]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
df=pd.read_html(url_mcc)
type(df)

# #If I want to specify that this particular column should be available in that table, then we need to writea as follows:
# url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
# df=pd.read_html(url_mcc,match='Country')

# Or we can simple change indexing in datafreame like I did below:



In [ ]:
df[1]

# Pickling

All pandas object are quipped with to_pickle methods with use python's cpickele module to save data structures to disk using the pickle format.

In [ ]:
df.to_pickle('pickle_file')

# Important functions in Pandas

Convert dataframe into numpy array: <br>
1) df.to_numpy <br>
2) df.T <br>
3) df.sort_index(axis=0,ascending=False) - Row wise Sorting <br>
4) df.sort_index(axis=1,ascending=False) - Column wise sorting <br>
5) df.reset_index(drop=True,inplace=True) - Reset Index <br>
6) df.iterrows() or zip(df['1st column'],df['2nd column']): in looop  <br>
7) df.drop('Column Name',axis0/1,inplace=True/False) axis0 - Rows, axis1 - columns  <br>
8) .str.contains('M') - Instr with 'M'  <br>
9) df.loc[~df['column name'].str.contains('M')] - Notinstr with M  <br>


Ingore case sensitive: <br>
import re <br>
10) .str.contains('name',flags=re.I,regex=True)  <br>
11) .str.contains('^M[a-z]',flags = re.I,regex = True)  <br>
12) df.sort_values('columnname,ascending=True/False)  <br>
13) df.append(values,ignore_index = True) - To add values in data frame  <br>
14) df.groupby('jissegrouping chahhiye').sum()[kis_column ka sum] <br>
15) df.drop(df.loc[df['columnname']>2].index,axis=0,inplace=True/False) - Remove list of rows based on some condition  <br>
16) df.fillna(value,axis=o/1,inplace=Ture/False) - Fill blank values with some values, Row wise & column wise <br>
17) df.reset_index(0) - To convert index in a column of the given dataframe  <br>
18) pd.concat([s1,s2]) - Concat two series and create one dataframe  <br>
19) df['columnname'].to_datetime(s) - To convert particular column into date time
20) df.rename(columns={'col1':'Newcolumnname'}) - To rename existing column name with new name  <br>
21) df.sort_values('columnname',ascending=Ture/False) - Sorting dataframe based on some column  <br>



# Important Points while creating data frame 

## First 3 points will remain same for all other files  <br>
1) Use_cols = Define which column we need to read while creating data frame <br>
2) Header = None/0/1/2 - Define which row you want to present as header in dataframe <br>
3) Index_col = False/0/1/2 - Define which column you want to present as index while creating dataframe <br>


###  - While creating dataframe from excel sheet <br>
4) Sheet_Name = Define which particular sheet you want to read while creating dataframe <br>

### - While creating dataframe from csv file <br>
5) sep = '/t', ',', ' ' - Define separator <br>

### - While creating dataframe from HTML table tag <br>
6) This will read all the tables present in particular HTML pasge. We need to use as follows:  <br>
df[o], df[1] , df[2] and so on .....  <br>




# Complex Pandas Codes

Concating 12 files of same format in once dataframe using loop <br>

import os  <br>
files = [file for file in os.listdir('path')] <br>
mdf = pd.Dataframe() <br>

for file in files: <br>
    df = pd.read_csv('path' + file) <br>
    mdf=pd.concat(mdf,df) <br>
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

1) df.dropna(axis=0,how='all/any/',inplace = True) - Removing NAN values from data frame <br>
2) df.drop(df.loc[df['Order Date].str[0:2]=='Or].index,axis = 0 , inplace=True) - Removig headers from all other files that include "or" from order date. <br>
3) df['columnname'].astype(int/float) <br>
    


## Query

How to use Lambda,transform,apply function in pandas with any of the columns